-- Catálogo de centros sanitarios
CREATE TABLE centro (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR2(255) NOT NULL UNIQUE
);

-- Circunstancia del contacto asistencial
CREATE TABLE circunstancia_contacto (
    id NUMBER(10) PRIMARY KEY,
    nombre VARCHAR2(255) NOT NULL
);

-- Comunidades autónomas
CREATE TABLE comunidad_autonoma (
    id NUMBER(10) PRIMARY KEY,
    nombre VARCHAR2(255) NOT NULL
);

-- Dispositivos de continuidad asistencial
CREATE TABLE continuidad_asistencial (
    id NUMBER(10) PRIMARY KEY,
    nombre VARCHAR2(255) NOT NULL
);

-- Catálogo de diagnósticos CIE-10
CREATE TABLE diagnostico (
    id NUMBER(10) PRIMARY KEY,
    codigo VARCHAR2(255) NOT NULL,
    nombre VARCHAR2(255)
);

CREATE UNIQUE INDEX diagnostico_codigo_idx ON diagnostico (codigo);

-- Marcadores POA (Present on Admission)
CREATE TABLE marcador_poa (
    id NUMBER(10) PRIMARY KEY,
    codigo VARCHAR2(255) NOT NULL,
    nombre VARCHAR2(255) NOT NULL
);

CREATE UNIQUE INDEX marcador_poa_codigo_idx ON marcador_poa (codigo);

-- Catálogo de países
CREATE TABLE pais (
    id NUMBER(10) PRIMARY KEY,
    codigo VARCHAR2(255) NOT NULL,
    nombre VARCHAR2(255) NOT NULL
);

CREATE UNIQUE INDEX pais_codigo_idx ON pais (codigo);

-- Procedencia del contacto
CREATE TABLE procedencia (
    id NUMBER(10) PRIMARY KEY,
    nombre VARCHAR2(255) NOT NULL
);

-- Catálogo de procedimientos CIE-10
CREATE TABLE procedimiento (
    id NUMBER(10) PRIMARY KEY,
    codigo VARCHAR2(255) NOT NULL,
    nombre VARCHAR2(255)
);

CREATE UNIQUE INDEX procedimiento_codigo_idx ON procedimiento (codigo);

-- Régimen de financiación del contacto
CREATE TABLE regimen_financiacion (
    id NUMBER(10) PRIMARY KEY,
    nombre VARCHAR2(255) NOT NULL
);

-- Servicios responsables de la atención
CREATE TABLE servicio (
    id NUMBER(10) PRIMARY KEY,
    codigo VARCHAR2(255) NOT NULL,
    nombre VARCHAR2(255) NOT NULL
);

CREATE UNIQUE INDEX servicio_codigo_idx ON servicio (codigo);

-- Identidad de género registrada
CREATE TABLE sexo (
    id NUMBER(10) PRIMARY KEY,
    nombre VARCHAR2(255) NOT NULL
);

-- Tipo de alta del episodio
CREATE TABLE tipo_alta (
    id NUMBER(10) PRIMARY KEY,
    nombre VARCHAR2(255) NOT NULL
);

-- Pacientes
CREATE TABLE paciente (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_nacimiento DATE,
    nss VARCHAR2(255),
    pais_nacimiento_id NUMBER(10) REFERENCES pais (id),
    sexo_id NUMBER(10) REFERENCES sexo (id)
);

CREATE INDEX paciente_pais_nacimiento_id_idx ON paciente (pais_nacimiento_id);
CREATE INDEX paciente_sexo_id_idx ON paciente (sexo_id);

-- Episodios de atención sanitaria
CREATE TABLE atencion_sanitaria (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    centro_id NUMBER(10) REFERENCES centro (id),
    circunstancia_contacto_id NUMBER(10) REFERENCES circunstancia_contacto (id),
    comunidad_autonoma_id NUMBER(10) REFERENCES comunidad_autonoma (id),
    continuidad_asistencial_id NUMBER(10) REFERENCES continuidad_asistencial (id),
    coste NUMBER(10),
    dias_uci NUMBER(10),
    fecha_alta DATE,
    fecha_ingreso DATE,
    fecha_intervencion DATE,
    nivel_severidad NUMBER(10),
    numero_registro NUMBER(10),
    paciente_id NUMBER(10) REFERENCES paciente (id),
    pais_residencia_id NUMBER(10) REFERENCES pais (id),
    procedencia_id NUMBER(10) REFERENCES procedencia (id),
    regimen_financiacion_id NUMBER(10) REFERENCES regimen_financiacion (id),
    riesgo_mortalidad NUMBER(10),
    servicio_id NUMBER(10) REFERENCES servicio (id),
    tipo_alta_id NUMBER(10) REFERENCES tipo_alta (id)
);

CREATE INDEX atencion_sanitaria_centro_id_idx ON atencion_sanitaria (centro_id);
CREATE INDEX atencion_sanitaria_circunstancia_contacto_id_idx ON atencion_sanitaria (circunstancia_contacto_id);
CREATE INDEX atencion_sanitaria_comunidad_autonoma_id_idx ON atencion_sanitaria (comunidad_autonoma_id);
CREATE INDEX atencion_sanitaria_continuidad_asistencial_id_idx ON atencion_sanitaria (continuidad_asistencial_id);
CREATE INDEX atencion_sanitaria_paciente_id_idx ON atencion_sanitaria (paciente_id);
CREATE INDEX atencion_sanitaria_pais_residencia_id_idx ON atencion_sanitaria (pais_residencia_id);
CREATE INDEX atencion_sanitaria_procedencia_id_idx ON atencion_sanitaria (procedencia_id);
CREATE INDEX atencion_sanitaria_regimen_financiacion_id_idx ON atencion_sanitaria (regimen_financiacion_id);
CREATE INDEX atencion_sanitaria_servicio_id_idx ON atencion_sanitaria (servicio_id);
CREATE INDEX atencion_sanitaria_tipo_alta_id_idx ON atencion_sanitaria (tipo_alta_id);

-- Diagnósticos asociados a la atención
CREATE TABLE atencion_sanitaria__diagnostico (
    atencion_sanitaria_id NUMBER(10) REFERENCES atencion_sanitaria (id),
    diagnostico_id NUMBER(10) REFERENCES diagnostico (id),
    marcador_poa NUMBER(10) REFERENCES marcador_poa (id),
    "number" NUMBER(10),
    PRIMARY KEY (atencion_sanitaria_id, diagnostico_id)
);

CREATE INDEX atencion_sanitaria__diagnostico_atencion_sanitaria_id_idx
    ON atencion_sanitaria__diagnostico (atencion_sanitaria_id);
CREATE INDEX atencion_sanitaria__diagnostico_diagnostico_id_idx
    ON atencion_sanitaria__diagnostico (diagnostico_id);
CREATE INDEX atencion_sanitaria__diagnostico_marcador_poa_idx
    ON atencion_sanitaria__diagnostico (marcador_poa);

-- Procedimientos realizados durante la atención
CREATE TABLE atencion_sanitaria__procedimiento (
    atencion_sanitaria_id NUMBER(10) REFERENCES atencion_sanitaria (id),
    procedimiento_id NUMBER(10) REFERENCES procedimiento (id),
    "number" NUMBER(10),
    PRIMARY KEY (atencion_sanitaria_id, procedimiento_id)
);

CREATE INDEX atencion_sanitaria__procedimiento_atencion_sanitaria_id_idx
    ON atencion_sanitaria__procedimiento (atencion_sanitaria_id);
CREATE INDEX atencion_sanitaria__procedimiento_procedimiento_id_idx
    ON atencion_sanitaria__procedimiento (procedimiento_id);

-- Procedimientos externos registrados para la atención
CREATE TABLE atencion_sanitaria__procedimiento_externo (
    atencion_sanitaria_id NUMBER(10) REFERENCES atencion_sanitaria (id),
    procedimiento_id NUMBER(10) REFERENCES procedimiento (id),
    "number" NUMBER(10),
    PRIMARY KEY (atencion_sanitaria_id, procedimiento_id)
);

CREATE INDEX atencion_sanitaria__procedimiento_externo_atencion_sanitaria_id
    ON atencion_sanitaria__procedimiento_externo (atencion_sanitaria_id);
CREATE INDEX atencion_sanitaria__procedimiento_externo_procedimiento_id_idx
    ON atencion_sanitaria__procedimiento_externo (procedimiento_id);
